spring:
  profiles:
    active: local
  config:
    import: classpath:oauth.yml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

    defer-datasource-initialization: true

  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug
