spring:
  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug
